"""
Trigger Registry for alert triggers.

Provides interface for Layer 4 intelligence triggers.
Implementation will be completed in Week 3-4.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict, Optional, List
from datetime import datetime
from dataclasses import dataclass
from enum import Enum
import logging

from src.registries.base import Registry

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class Alert:
    """
    Alert generated by a trigger.

    Represents an actionable insight or warning.
    """
    trigger_id: str
    trigger_type: str
    severity: AlertSeverity
    title: str
    message: str
    timestamp: datetime
    data: Optional[Dict[str, Any]] = None

    def to_dict(self) -> dict:
        return {
            'trigger_id': self.trigger_id,
            'trigger_type': self.trigger_type,
            'severity': self.severity.value,
            'title': self.title,
            'message': self.message,
            'timestamp': self.timestamp.isoformat(),
            'data': self.data
        }


class Trigger(ABC):
    """
    Abstract base class for all triggers.

    Triggers evaluate data and generate alerts based on conditions.
    """

    @abstractmethod
    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate data and return any triggered alerts.

        Args:
            data: Input data to evaluate
            config: Optional trigger configuration

        Returns:
            List of triggered alerts (empty if none)
        """
        pass

    @property
    @abstractmethod
    def trigger_type(self) -> str:
        """
        Return the type of trigger.

        Returns:
            One of: 'protocol', 'estate', 'whale', 'regime', 'correlation'
        """
        pass

    def get_name(self) -> str:
        """Get the trigger name for logging."""
        return self.__class__.__name__


class TriggerRegistry(Registry[Trigger]):
    """
    Registry for alert triggers.

    Usage:
        trigger = TriggerRegistry.get_instance().get("protocol_health", {})
        alerts = trigger.evaluate(data)
    """
    pass


# =============================================================================
# Stub Implementations (to be completed in Week 3-4)
# =============================================================================

@TriggerRegistry.register("protocol_health")
class ProtocolHealthTrigger(Trigger):
    """
    Trigger alerts on protocol health changes.

    Monitors:
    - TVL drops (>10% warning, >25% critical)
    - APY spikes (>3 std dev from mean)
    - Utilization rate changes
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.tvl_warning_threshold = config.get('tvl_warning_threshold', 0.10)
        self.tvl_critical_threshold = config.get('tvl_critical_threshold', 0.25)
        self.apy_std_threshold = config.get('apy_std_threshold', 3.0)

    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate protocol health and generate alerts.

        Args:
            data: Dict with protocol metrics:
                - current: Current metrics (tvl, apy, utilization)
                - previous: Previous metrics for comparison

        Returns:
            List of triggered alerts
        """
        alerts = []

        # Stub implementation - will be completed in Week 3-4
        logger.debug("ProtocolHealthTrigger.evaluate() - stub implementation")

        return alerts

    @property
    def trigger_type(self) -> str:
        return "protocol"


@TriggerRegistry.register("regime_change")
class RegimeChangeTrigger(Trigger):
    """
    Trigger alerts on market regime changes.

    Monitors transitions between:
    - Bull → Bear
    - Bear → Crash
    - Crash → Recovery
    - Recovery → Bull
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.confidence_threshold = config.get('confidence_threshold', 0.7)

    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate market regime and generate alerts on changes.

        Args:
            data: Dict with regime data:
                - current_regime: Current detected regime
                - previous_regime: Previous regime
                - confidence: Detection confidence

        Returns:
            List of triggered alerts
        """
        alerts = []

        # Stub implementation - will be completed in Week 3-4
        logger.debug("RegimeChangeTrigger.evaluate() - stub implementation")

        return alerts

    @property
    def trigger_type(self) -> str:
        return "regime"


@TriggerRegistry.register("estate_movement")
class EstateMovementTrigger(Trigger):
    """
    Trigger alerts on estate wallet movements.

    Monitors:
    - FTX estate distributions
    - Mt. Gox distributions
    - Genesis distributions
    - Large wallet movements
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.movement_threshold = config.get('movement_threshold', 1_000_000)  # $1M USD

    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate estate wallet activity and generate alerts.

        Args:
            data: Dict with estate data:
                - wallets: List of tracked wallet addresses
                - transactions: Recent transactions
                - balances: Current balances

        Returns:
            List of triggered alerts
        """
        alerts = []

        # Stub implementation - will be completed in Week 3-4
        logger.debug("EstateMovementTrigger.evaluate() - stub implementation")

        return alerts

    @property
    def trigger_type(self) -> str:
        return "estate"


@TriggerRegistry.register("whale_activity")
class WhaleActivityTrigger(Trigger):
    """
    Trigger alerts on whale wallet activity.

    Monitors:
    - Large accumulation
    - Large distribution
    - Exchange inflows/outflows
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.whale_threshold = config.get('whale_threshold', 10_000_000)  # $10M USD

    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate whale activity and generate alerts.

        Args:
            data: Dict with whale data:
                - wallets: Tracked whale addresses
                - transactions: Recent large transactions
                - exchange_flows: Exchange inflow/outflow data

        Returns:
            List of triggered alerts
        """
        alerts = []

        # Stub implementation - will be completed in Week 3-4
        logger.debug("WhaleActivityTrigger.evaluate() - stub implementation")

        return alerts

    @property
    def trigger_type(self) -> str:
        return "whale"


@TriggerRegistry.register("correlation_break")
class CorrelationBreakTrigger(Trigger):
    """
    Trigger alerts on correlation breakdowns.

    Monitors:
    - SOL-ETH correlation changes
    - SOL-BTC correlation changes
    - ETH-BTC correlation changes
    - Risk-on/risk-off correlation shifts
    """

    def __init__(self, config: Dict[str, Any]):
        self.config = config
        self.correlation_change_threshold = config.get('correlation_change_threshold', 0.3)

    def evaluate(self, data: Dict[str, Any], config: Optional[Dict[str, Any]] = None) -> List[Alert]:
        """
        Evaluate correlations and generate alerts on significant changes.

        Args:
            data: Dict with correlation data:
                - current_correlations: Current correlation matrix
                - historical_correlations: Historical baselines

        Returns:
            List of triggered alerts
        """
        alerts = []

        # Stub implementation - will be completed in Week 3-4
        logger.debug("CorrelationBreakTrigger.evaluate() - stub implementation")

        return alerts

    @property
    def trigger_type(self) -> str:
        return "correlation"
