"""
Markdown Reporter for human-readable reports.
"""

from pathlib import Path
from datetime import datetime
from typing import Optional
import logging

from src.domain.simulation import BattleTestResult, MonteCarloResult
from src.utils.file_io import safe_write_text
from src.adelaide.localization import HYPOTHETICAL_DISCLAIMERS
from src.utils.audit import get_audit_trail
from config.settings import OUTPUT_DIR

logger = logging.getLogger(__name__)


class MarkdownReporter:
    """Generate human-readable Markdown reports."""

    def __init__(self, output_dir: Path = None):
        self.output_dir = output_dir or OUTPUT_DIR

    def generate_battle_test_report(
        self,
        results: list[BattleTestResult],
        scenario: str = 'A',
        filename: str = 'battle_test_report.md'
    ) -> Path:
        """
        Generate Battle Test report in Markdown.

        Args:
            results: List of BattleTestResult
            scenario: Scenario identifier
            filename: Output filename

        Returns:
            Path to output file
        """
        output_path = self.output_dir / filename

        lines = [
            "# Battle Test Report",
            "",
            f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Scenario:** {scenario}",
            "",
            "## Summary",
            "",
            "Historical backtesting of 10 diBoaS investment strategies from May 2022 to December 2025.",
            "",
            "### Key Events in Test Period",
            "- Terra/Luna collapse (May 2022)",
            "- FTX crash (November 2022)",
            "- USDC depeg (March 2023)",
            "",
            "## Results",
            "",
            "| Strategy | Crypto % | Return | Max Drawdown | Final Value |",
            "|----------|----------|--------|--------------|-------------|"
        ]

        for r in sorted(results, key=lambda x: x.strategy_id):
            crypto_pct = self._get_crypto_pct(r.strategy_id)
            lines.append(
                f"| {r.strategy_name} | {crypto_pct}% | "
                f"{r.return_pct:+.1f}% | {r.max_drawdown_pct:.1f}% | "
                f"${r.final_value:,.0f} |"
            )

        lines.extend([
            "",
            "## Key Findings",
            "",
            "### Stable Strategies (0% Crypto)",
            ""
        ])

        stable_results = [r for r in results if self._get_crypto_pct(r.strategy_id) == 0]
        if stable_results:
            avg_return = sum(r.return_pct for r in stable_results) / len(stable_results)
            max_dd = max(r.max_drawdown_pct for r in stable_results)
            lines.append(f"- Average return: **{avg_return:.1f}%**")
            lines.append(f"- Maximum drawdown: **{max_dd:.1f}%**")
            lines.append("- All stable strategies maintained 0% drawdown through market crashes")

        lines.extend([
            "",
            "### Crypto-Exposed Strategies",
            ""
        ])

        crypto_results = [r for r in results if self._get_crypto_pct(r.strategy_id) > 0]
        if crypto_results:
            best = max(crypto_results, key=lambda x: x.return_pct)
            worst_dd = max(crypto_results, key=lambda x: x.max_drawdown_pct)
            lines.append(f"- Best performer: **{best.strategy_name}** ({best.return_pct:+.1f}%)")
            lines.append(f"- Highest drawdown: **{worst_dd.strategy_name}** ({worst_dd.max_drawdown_pct:.1f}%)")

        lines.extend([
            "",
            "## Methodology",
            "",
            "- **Period:** May 1, 2022 - December 31, 2025 (1,334 days)",
            "- **Strategy:** Dollar-cost averaging with monthly contributions",
            "- **Data sources:** DeFiLlama (APY), Yahoo Finance (prices), Jupiter (JLP)",
            "- **Proxy formulas:** QR Board validated for missing historical data",
            "",
            "---",
            "",
            "## Hypothetical Performance Notice",
            "",
            HYPOTHETICAL_DISCLAIMERS['en'],
            "",
            "---",
            f"*Report generated by diBoaS Analytics v1.0*"
        ])

        safe_write_text('\n'.join(lines), output_path)

        # Log output file to audit trail
        audit = get_audit_trail()
        if audit:
            audit.log_output_file(output_path)

        logger.info(f"Battle Test report exported to {output_path}")
        return output_path

    def generate_monte_carlo_report(
        self,
        results: list[MonteCarloResult],
        filename: str = 'monte_carlo_report.md'
    ) -> Path:
        """
        Generate Monte Carlo report in Markdown.

        Args:
            results: List of MonteCarloResult
            filename: Output filename

        Returns:
            Path to output file
        """
        output_path = self.output_dir / filename

        lines = [
            "# Monte Carlo Simulation Report",
            "",
            f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            "",
            "## Summary",
            "",
            "Forward-looking risk analysis using 5,000 simulations per strategy.",
            "",
            "### Methodology",
            "- Regime-switching model (Bull, Bear, Crash, Recovery)",
            "- Fat-tailed distributions (Student-t, df=4)",
            "- 48-month horizon with monthly DCA",
            "",
            "## Risk Metrics",
            "",
            "| Strategy | Median Return | P(Loss) | P(>10% Loss) | VaR 95% |",
            "|----------|---------------|---------|--------------|---------|"
        ]

        for r in sorted(results, key=lambda x: x.strategy_id):
            lines.append(
                f"| {r.strategy_name} | {r.median_return:+.1f}% | "
                f"{r.prob_any_loss:.1f}% | {r.prob_loss_10pct:.1f}% | "
                f"${r.var_95:,.0f} |"
            )

        lines.extend([
            "",
            "## Probability of Loss Analysis",
            "",
            "### Stable Strategies (0% Crypto)",
            ""
        ])

        stable_results = [r for r in results if self._get_crypto_pct(r.strategy_id) == 0]
        if stable_results:
            avg_prob = sum(r.prob_any_loss for r in stable_results) / len(stable_results)
            lines.append(f"- Average probability of any loss: **{avg_prob:.1f}%**")
            lines.append("- Stable strategies show near-zero probability of loss")

        lines.extend([
            "",
            "### High-Risk Strategies",
            ""
        ])

        high_risk = [r for r in results if r.strategy_id in [8, 10]]
        for r in high_risk:
            lines.append(f"**{r.strategy_name}:**")
            lines.append(f"- Probability of any loss: {r.prob_any_loss:.1f}%")
            lines.append(f"- Probability of >50% loss: {r.prob_loss_50pct:.1f}%")
            lines.append(f"- 90% confidence interval: ${r.p5_final:,.0f} to ${r.p95_final:,.0f}")
            lines.append("")

        lines.extend([
            "## Recommendations",
            "",
            "1. **Conservative users (Ana):** Strategies 1, 3, 5 offer stable returns with minimal risk",
            "2. **Moderate users (Maria):** Strategies 2, 4, 6 balance growth and safety",
            "3. **Aggressive users (Felipe):** Strategies 8, 10 for maximum growth potential",
            "",
            "---",
            "",
            "## Hypothetical Performance Notice",
            "",
            HYPOTHETICAL_DISCLAIMERS['en'],
            "",
            "---",
            f"*Report generated by diBoaS Analytics v1.0*"
        ])

        safe_write_text('\n'.join(lines), output_path)

        # Log output file to audit trail
        audit = get_audit_trail()
        if audit:
            audit.log_output_file(output_path)

        logger.info(f"Monte Carlo report exported to {output_path}")
        return output_path

    def _get_crypto_pct(self, strategy_id: int) -> int:
        """Get crypto percentage for a strategy."""
        crypto_pcts = {
            1: 0, 2: 30, 3: 0, 4: 35, 5: 0,
            6: 40, 7: 0, 8: 70, 9: 0, 10: 85
        }
        return crypto_pcts.get(strategy_id, 0)


def generate_combined_report(
    bt_results: list[BattleTestResult],
    mc_results: list[MonteCarloResult],
    output_dir: Path = None
) -> dict[str, Path]:
    """
    Generate all reports.

    Returns:
        Dictionary of report type -> file path
    """
    reporter = MarkdownReporter(output_dir)

    return {
        'battle_test': reporter.generate_battle_test_report(bt_results),
        'monte_carlo': reporter.generate_monte_carlo_report(mc_results)
    }
